export default {
  login: 'aacismaharjan',
  id: 44110105,
  node_id: 'MDQ6VXNlcjQ0MTEwMTA1',
  avatar_url: 'https://avatars0.githubusercontent.com/u/44110105?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/aacismaharjan',
  html_url: 'https://github.com/aacismaharjan',
  followers_url: 'https://api.github.com/users/aacismaharjan/followers',
  following_url:
    'https://api.github.com/users/aacismaharjan/following{/other_user}',
  gists_url: 'https://api.github.com/users/aacismaharjan/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/aacismaharjan/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/aacismaharjan/subscriptions',
  organizations_url: 'https://api.github.com/users/aacismaharjan/orgs',
  repos_url: 'https://api.github.com/users/aacismaharjan/repos',
  events_url: 'https://api.github.com/users/aacismaharjan/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/aacismaharjan/received_events',
  type: 'User',
  site_admin: false,
  name: 'Aashish Maharjan',
  company: 'Student',
  blog: 'https://aacismaharjan.github.io/',
  location: 'Nepal',
  email: null,
  hireable: true,
  bio: 'Having fun with javascript!',
  twitter_username: 'aacismhrzn',
  public_repos: 20,
  public_gists: 0,
  followers: 2,
  following: 37,
  created_at: '2018-10-13T07:02:26Z',
  updated_at: '2020-10-04T03:12:15Z',
}
